language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN="69ae7bc7-e506-47c8-82c9-2f529bba01b0"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - kostasc@mail.ru
    on_success: never # default: change
    on_failure: always # default: always